import { faker } from '@faker-js/faker';

let userCounter = 0, projectCounter = 0, eventCounter = 0, tagCounter = 0;
let dashboardCounter = 0, indicatorCounter = 0, alertRuleCounter = 0, financeCounter = 0, kocrmCounter = 0;

export const factories = {
  user: (o = {}) => ({ id: `user-${++userCounter}-${faker.string.uuid()}`, email: faker.internet.email(), username: faker.internet.username(), displayName: faker.person.fullName(), avatarUrl: faker.image.avatar(), role: faker.helpers.arrayElement(['admin','manager','analyst','viewer','operator']), status: faker.helpers.arrayElement(['active','inactive','locked']), lastLoginAt: faker.date.recent(), createdAt: faker.date.past(), updatedAt: faker.date.recent(), ...o }),
  project: (o = {}) => ({ id: `project-${++projectCounter}-${faker.string.uuid()}`, code: `proj_${faker.string.alphanumeric(8)}`, name: faker.company.name(), description: faker.lorem.sentence(), status: faker.helpers.arrayElement(['active','inactive','archived','draft']), ownerId: `user-${faker.number.int({min:1,max:userCounter||1})}-${faker.string.uuid()}`, timezone: 'Asia/Shanghai', locale: 'zh-CN', settings: {}, createdAt: faker.date.past(), updatedAt: faker.date.recent(), ...o }),
  event: (o = {}) => ({ id: `event-${++eventCounter}-${faker.string.uuid()}`, projectId: `project-${faker.number.int({min:1,max:projectCounter||1})}-${faker.string.uuid()}`, code: `evt_${faker.string.alphanumeric(8)}`, name: faker.lorem.words(3), description: faker.lorem.sentence(), categoryId: faker.datatype.boolean()?`category-${faker.string.uuid()}`:null, status: faker.helpers.arrayElement(['draft','pending_review','approved','rejected','published','archived']), version: faker.number.int({min:1,max:10}), properties: {}, createdBy: `user-${faker.number.int({min:1,max:userCounter||1})}-${faker.string.uuid()}`, approvedBy: null, approvedAt: null, createdAt: faker.date.past(), updatedAt: faker.date.recent(), ...o }),
  tag: (o = {}) => ({ id: `tag-${++tagCounter}-${faker.string.uuid()}`, projectId: `project-${faker.number.int({min:1,max:projectCounter||1})}-${faker.string.uuid()}`, name: faker.lorem.words(2), description: faker.lorem.sentence(), type: faker.helpers.arrayElement(['sql','condition','indicator','first_last','id']), definition: {}, groupId: null, isActive: faker.datatype.boolean(), createdBy: `user-${faker.number.int({min:1,max:userCounter||1})}-${faker.string.uuid()}`, createdAt: faker.date.past(), updatedAt: faker.date.recent(), ...o }),
  dashboard: (o = {}) => ({ id: `dashboard-${++dashboardCounter}-${faker.string.uuid()}`, projectId: `project-${faker.number.int({min:1,max:projectCounter||1})}-${faker.string.uuid()}`, name: faker.lorem.words(3), description: faker.lorem.sentence(), layout: faker.helpers.arrayElement(['grid','free','responsive']), layoutConfig: {}, isPublic: faker.datatype.boolean(), tags: [], createdBy: `user-${faker.number.int({min:1,max:userCounter||1})}-${faker.string.uuid()}`, createdAt: faker.date.past(), updatedAt: faker.date.recent(), ...o }),
  indicator: (o = {}) => ({ id: `indicator-${++indicatorCounter}-${faker.string.uuid()}`, projectId: `project-${faker.number.int({min:1,max:projectCounter||1})}-${faker.string.uuid()}`, code: `ind_${faker.string.alphanumeric(8)}`, name: faker.lorem.words(3), description: faker.lorem.sentence(), formula: 'count(*)', unit: 'count', precision: 2, categoryId: null, ownerId: `user-${faker.number.int({min:1,max:userCounter||1})}-${faker.string.uuid()}`, isActive: faker.datatype.boolean(), createdAt: faker.date.past(), updatedAt: faker.date.recent(), ...o }),
  alertRule: (o = {}) => ({ id: `alert-${++alertRuleCounter}-${faker.string.uuid()}`, projectId: `project-${faker.number.int({min:1,max:projectCounter||1})}-${faker.string.uuid()}`, name: faker.lorem.words(3), description: faker.lorem.sentence(), indicatorId: `indicator-${faker.number.int({min:1,max:indicatorCounter||1})}-${faker.string.uuid()}`, condition: { operator: faker.helpers.arrayElement(['gt','gte','lt','lte','eq','neq']), threshold: faker.number.float({min:10,max:10000,fractionDigits:2}) }, severity: faker.helpers.arrayElement(['info','warning','critical','emergency']), channels: faker.helpers.arrayElements(['email','webhook','dingtalk','feishu','sms'],{min:1,max:3}), recipients: Array.from({length:faker.number.int({min:1,max:5})},()=>faker.internet.email()), schedule: { cron: '0 * * * *' }, isActive: faker.datatype.boolean(), createdBy: `user-${faker.number.int({min:1,max:userCounter||1})}-${faker.string.uuid()}`, createdAt: faker.date.past(), updatedAt: faker.date.recent(), ...o }),
  financeRecord: (o = {}) => ({ id: `finance-${++financeCounter}-${faker.string.uuid()}`, projectId: `project-${faker.number.int({min:1,max:projectCounter||1})}-${faker.string.uuid()}`, type: faker.helpers.arrayElement(['receivable','payable','revenue','cost','asset','liability']), amount: faker.number.float({min:1,max:1000000,fractionDigits:2}), currency: 'CNY', exchangeRate: 1, accountId: `account-${faker.string.uuid()}`, counterparty: faker.company.name(), description: faker.lorem.sentence(), invoiceNumber: `INV-${faker.string.alphanumeric(8).toUpperCase()}`, invoiceDate: faker.date.past(), dueDate: faker.date.future(), status: faker.helpers.arrayElement(['pending','partial','paid','overdue','cancelled']), createdBy: `user-${faker.number.int({min:1,max:userCounter||1})}-${faker.string.uuid()}`, createdAt: faker.date.past(), updatedAt: faker.date.recent(), ...o }),
  kocrmRecord: (o = {}) => { const ch = faker.helpers.arrayElement(['douyin','kuaishou','xiaohongshu','wechat','bilibili','weibo']); return { id: `kocrm-${++kocrmCounter}-${faker.string.uuid()}`, projectId: `project-${faker.number.int({min:1,max:projectCounter||1})}-${faker.string.uuid()}`, channel: ch, accountId: faker.string.alphanumeric(12), accountName: `${faker.person.firstName()}_${ch}`, campaignId: faker.string.alphanumeric(10), materialId: faker.string.alphanumeric(10), metrics: { views: faker.number.int({min:0,max:1000000}), clicks: faker.number.int({min:0,max:100000}), likes: faker.number.int({min:0,max:50000}), comments: faker.number.int({min:0,max:10000}), shares: faker.number.int({min:0,max:5000}) }, cost: faker.number.float({min:0,max:100000,fractionDigits:2}), revenue: faker.number.float({min:0,max:200000,fractionDigits:2}), date: faker.date.recent(), createdAt: faker.date.past(), updatedAt: faker.date.recent(), ...o }; },
  createMany: <T>(factory: () => T, count: number): T[] => Array.from({length:count}, factory),
  resetCounters: () => { userCounter=0; projectCounter=0; eventCounter=0; tagCounter=0; dashboardCounter=0; indicatorCounter=0; alertRuleCounter=0; financeCounter=0; kocrmCounter=0; },
};

export const { user, project, event, tag, dashboard, indicator, alertRule, financeRecord, kocrmRecord, createMany, resetCounters } = factories;